# directory or S3 bucket + prefix where created reports are stored.
output_dir: s3://bmonreporter/reports-test

# a list or iterable containing the base BMON Server URLs that should be 
# processed for creating reports.  e.g. ['https://bms.ahfc.us', 'https://bmon.analysisnorth.com']
bmon_urls: 
  - https://bms.ahfc.us
#  - https://bmon.analysisnorth.com

# The jupyter themes command to execute before creating the reports
jup_theme_cmd: jt -t grade3 -cellw 95% -lineh 150 -fs 105 -nfs 120 -tfs 130 -dfs 100 -ofs 100
